language: go

matrix:
  include:
    - go: 1.8.x
    - master

before_install:
  - go get -t -v ./...
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -race -v ./...
  - go test -coverprofile=mimetypes.coverprofile
  - gover
  - goveralls -coverprofile=mimetypes.coverprofile -service=travis-ci

notifications:
  email:
    on_success: never